version: "2"

services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    #command: [nginx-debug, '-g', 'daemon off;']

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  web-https:
    restart: always
    image: nginx:alpine
    container_name: web-https
    volumes:
      - "./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
      - "./volumes/nginx-sample-website/html/:/usr/share/nginx/html"
    environment:
      #- VIRTUAL_HOST=sample.com,www.sample.com,files.sample.com
      - VIRTUAL_HOST=files.sample.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=files.sample.com
      - LETSENCRYPT_EMAIL=sample@sample.com
      #- LETSENCRYPT_TEST=true
      #- ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory

  sample-api:
    restart: always
    image: sample-api
    build: ./samples/api
    container_name: sample-api
    volumes:
      - "./volumes/nginx-sample-website/static:/home/app/src/public:ro"
    environment:
      - VIRTUAL_HOST=api.sample.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.sample.com
      - LETSENCRYPT_EMAIL=sample@sample.com
